node{
    def workspace_dir = 'webapp'
    def operation = "${OPERATION}"
    stage("Git checkout"){
        checkout(
            [
                $class: 'GitSCM',
                branches: [[name: "${BRANCH_NAME}"]],
                extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: workspace_dir]],
                userRemoteConfigs: [[url: "${SCM_GIT_URL}", credentialsId: "${CREDENTIALS_ID}"]]
            ]
        )
        println("Git Checkout Success")
    }
}