node{
    def workspace_dir = 'webapp'
    def operation = "${OPERATION}"
    stage("Git checkout"){
        checkout(
            [
                $class: 'GitSCM',
                branches: [[name: "${BRANCH_NAME}"]],
                extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: workspace_dir]],
                userRemoteConfigs: [[url: "${SCM_GIT_URL}", credentialsId: "${CREDENTIALS_ID}"]]
            ]
        )
        println("Git Checkout Success")
    }

    stage('Download Terraform'){
        sh ('''
            #!/bin/bash
            if [! -d ${JENKINS_HOME}/project/terraform]; then
                echo $PWD
                echo ${JENKINS_HOME}
                mkdir -p ${JENKINS_HOME}/project/terraform
                cd ${JENKINS_HOME}/project/terraform
            else
                echo "Terraform directory created"
            fi
        ''')
    }

    stage('Install Terraform'){
        dir(workspace_dir) {
            sh ('''
                #!/bin/bash
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update && sudo apt-get install terraform
                terrafom -v
            ''')
        }
    }
}