node{
    def workspace_dir = 'webapp'
    def operation = "${OPERATION}"
    stage("Git checkout"){
        checkout(
            [
                $class: 'GitSCM',
                branches: [[name: "${BRANCH_NAME}"]],
                extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: workspace_dir]],
                userRemoteConfigs: [[url: "${SCM_GIT_URL}", credentialsId: "${CREDENTIALS_ID}"]]
            ]
        )
        println("Git Checkout Success")
    }

    stage('Download Terraform'){
        sh ('''
            #!/bin/bash
            if [! -d ${JENKINS_HOME}/project/terraform]; then
                echo $PWD
                echo ${JENKINS_HOME}
                mkdir -p ${JENKINS_HOME}/project/terraform
                cd ${JENKINS_HOME}/project/terraform
            else
                echo "Terraform directory created"
            fi
        ''')
    }
}